
  <script type="text/javascript">
        $(function() {
            $("#form").validity(function() {                
                $("#Nombre").maxLength(50).minLength(2).require();
                $("#Descripcion").maxLength(100);               
                $("#Iniciales").maxLength(3);
                $("#Color").match("number");
            });    
        });    
    </script>

	 <?php
    if(isset($_GET["st"]))
    {
        mensaje($_GET['st']);
    }
	echo $ruta;
    ?>
    
    <h2>Editar Categoria</h2>
        
    <form action="" method="post" name="form" id="form">
            <p>
            <label>            
                <a href="<?php echo BASE_URL;?>?accion=cat&p=<?php echo $datos[0]["idPadre"]; ?>" class="btn btn-success"><span class="glyphicon glyphicon-arrow-left"></span> Regresar</a>
            </label>
            </p>

            <div class="form-group">
            <label>Categoria Padre (*)</label>
            <?php echo $selCategorias; ?>
            </div>
            <div class="form-group">
            <label>Nombre (*)</label>
            <input name="Nombre" id="Nombre" type="text" title="Nombre" class="form-control input-medium" value="<?php echo $datos[0]["Nombre"];?>"  />
            </div>
            <div class="form-group">
            <label>Descripcion</label>
            <input name="Descripcion" id="Descripcion" type="text" title="Nombre" class="form-control" value="<?php echo $datos[0]["Descripcion"];?>" />
            </div>            
            <div class="form-group">
            <label>Ruta de Imagenes</label>
            <input name="ImgPath" id="ImgPath" type="text" title="ImgPath" class="form-control input-small" value="<?php echo $datos[0]["ImgPath"];?>" />
            </div>
            <div class="form-group">
            <label>Iniciales (por defecto usadas en codigos de productos)</label>
            <input name="Iniciales" id="Iniciales" type="text" title="Iniciales" class="form-control input-small" value="<?php echo $datos[0]["Iniciales"];?>" />
            </div>
            <div class="form-group">
            <label>Color de Categoria</label>
            <input name="Color" id="Color" type="text" title="Color" class="form-control input-small" value="<?php echo $datos[0]["Color"];?>" />
            </div>           
            <div class="checkbox">
            <label>
                <input type="checkbox" class="checkbox" value="1" <?php if($datos[0]["Publicar"]==1) echo 'checked="checked"';?> title="Publicar" name="Publicar" id="Publicar" />
            Publicar
            </label>
            </div>                    
 
            <input type="hidden" name="id" value="<?php echo $datos[0]["idCategoria"]?>"/>
            <input type="hidden" name="grabar" value="si" />            
            <input type="submit" class="btn btn-primary" value="Guardar" title="Guardar cambios" />
            </p>
            </form>

