
  <script type="text/javascript">
        $(function() {
            $("#form").validity(function() {                
                $("#Nombre").maxLength(50).minLength(2).require();
                $("#Descripcion").maxLength(100);               
                $("#Iniciales").maxLength(3);
                $("#Color").match("number");
            });    
        });    
    </script>

	 <?php
    if(isset($_GET["st"]))
    {    	
        mensaje($_GET["st"]);
    }
	
    echo $ruta;?>    
        
        <h3>Agregar Categoria</h3>
        
    <form action="" method="post" name="form" id="form">
            <div class="form-group">            
            <a href="<?php echo BASE_URL;?>?accion=cat&p=<?php echo $padre;?>" title="Regresar" class="btn btn-success"><span class="glyphicon glyphicon-arrow-left" aria-hidden="true"></span> Volver</a>
            </div>

            <div class="form-group">
            <label>Categoria Padre (*)</label>
            <?php echo $selCategorias; ?>
            </div>
            <div class="form-group">
            <label>Nombre (*)</label>
            <input name="Nombre" id="Nombre" type="text" title="Nombre" class="input-medium form-control"  />
            </div>
            <div class="form-group">
            <label>Descripcion</label>
            <input name="Descripcion" id="Descripcion" type="text" title="Nombre" class="form-control"  />
            </div>            
            <div class="form-group">
            <label>Ruta de Imagenes</label>
            <input name="ImgPath" id="ImgPath" type="text" title="ImgPath" class="input-small form-control"  />
            </div>
            <div class="form-group">
            <label>Iniciales (por defecto usadas en codigos de productos)</label>
            <input name="Iniciales" id="Iniciales" type="text" title="Iniciales" class="form-control input-small"  />
            </div>
            <div class="form-group">
            <label>Color de Categoria</label>
            <input name="Color" id="Color" type="text" title="Color" class="form-control input-small"  />
            </div>           
            <div class="checkbox"><label>
            <input type="checkbox" value="1" checked="checked" title="Publicar" name="Publicar" id="Publicar" />
            Publicar</label>
            </div>                    
 
            <input type="hidden" name="p" value="<?php echo $padre;?>"/>
            <input type="hidden" name="grabar" value="si" />            
            <input type="submit" class="btn btn-primary" value="Agregar Categoria" title="Crear Nueva Categoria" />
            </div>
            </form>

