<?php
    if(isset($_GET["st"]))
    {
    	mensaje($_GET['st']);
    }
	?>
    
	<?php echo $ruta;?>    
    
     <h2>Categorias</h2>     
     <table>
        <tr>
		<td valign="middle" align="left" colspan="10">
		<a href="<?php echo BASE_URL;?>?accion=cat&p=<?php echo $idpadre;?>" title="Agregar nueva subcategoria" class="btn btn-success"><span class="glyphicon glyphicon-arrow-left" aria-hidden="true"></span> Volver</a>
		<a href="<?php echo BASE_URL;?>?accion=cat-add&p=<?php echo $idCat;?>" title="Agregar nueva subcategoria" class="btn btn-danger"><span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Agregar Categoria</a>
		
		</td>
		</tr> 
     </table>
     
     <table id="tabla"  class="tablesorter" >        
        <thead> 	
            <tr  style="font-weight: bold;">
            <th align="center">id</th>
            <th align="center">Nombre</th>
            <th align="center">Sub</th>
            <th align="center">Publicar</th>
            
            <th align="center">Editar</th>
            <th align="center">Eliminar</th>
            </tr>
        </thead> 
        <tbody> 
        <?php  
         
        for($i=0;$i<sizeof($datos);$i++)
        {
        ?>
         <tr>
        <td align="center"><?php echo $datos[$i]["idCategoria"];?></td>
        <td align="left"><?php echo $datos[$i]["Nombre"];?></td>
        <td align="center" ><a href="<?php echo BASE_URL . '?accion=cat&p=' . $datos[$i]["idCategoria"];?>">Ver..</a></td>
        <td align="center"><?php echo $datos[$i]["Publicar"];?></td>
        
        <td align="center"><a href="<?php echo BASE_URL;?>?accion=cat-edit&id=<?php echo $datos[$i]["idCategoria"];?>" title="Editar <?php echo $datos[$i]["Nombre"];?>"><img src="<?php echo PATH_IMG;?>b_edit.png" border="0" width="16" height="16"></a></td>
        <td align="center"><a href="javascript:void(0);" title="Eliminar <?php echo $datos[$i]["Nombre"];?>" onclick="eliminar('<?php echo BASE_URL;?>?accion=cat-del&id=<?php echo $datos[$i]["idCategoria"]."&p=".$idCat;?>')" ><img src="<?php echo PATH_IMG;?>b_drop.png" border="0" width="16" height="16"></a></td>
        </tr>
        <?php
        }
        ?>
        </tbody>
     </table>    
     
     <?php echo "<strong>" .sizeof($datos). " Registros encontrados.</strong>"; ?>  
    
    <script type="text/javascript" defer="defer">
    	$(document).ready(function() 
        { 
            $("#tabla").tablesorter({
                        theme : 'blue',
                        widgets: ["zebra"],                        
                        headers : { 4 : { sorter: false }, 5 : { sorter: false } }
            });
        } 
    	); 
    </script>    
