
  <script type="text/javascript">
        $(function() {
            $("#form").validity(function() {
                
                $("#Nombre").minLength(3).require();
                $("#Email").match("email");                
                $("#Tel").match("number");               
                $("#Cp").match("number");                
                $("#idSucursal").greaterThan( 0, "Debes seleccionar una opcion" ).require();                
            });    
        });    
    </script>

	 <?php
    if(isset($_GET["st"]))
    {
    	switch ($_GET["st"])
    	{
    		case '1':
    			?>
    			<div class="fail large png_bg">Complete todos los campos obligatorios por favor.</div>
    			<?php
    		break;
            
    		case '2':
    			?>
    			<div class="success large png_bg">El registro se ha editado exitosamente.</div>
    			<?php
    		break;
            case '3':
    			?>
    			<div class="fail large png_bg">Error, registro no editado.</div>
    			<?php
    		break;
    		
    	}
    }
	?>
        <h2>Editar Desposito</h2>
        
    <form action="" method="post" name="form" id="form">
            <p>
            <label><a href="<?php echo BASE_URL;?>?accion=dep"><img src="<?php echo PATH_IMG;?>arrow_left_32.png" border="0" width="24" height="24"></a></label>
            </p>

            <p>
            <label>Sucursal a la que pertenece (*)</label>
            <?php echo $selsucursal;?>
            </p>
            <p>
            <label>Nombre (*)</label>
            <input name="Nombre" id="Nombre" value="<?php echo $datos[0]["Nombre"];?>" type="text" class="input medium"  />
            </p>
            <p>
            <label>Descripcion</label>
            <input name="Descripcion" id="Descripcion" value="<?php echo $datos[0]["Descripcion"];?>" type="text" class="input large"  />
            </p>
            <p>
            <label>E-Mail</label>
            <input name="Email" id="Email" value="<?php echo $datos[0]["Email"];?>" type="text" class="input medium"  />
            </p>
            <p>
            <label>Dom</label>
            <input name="Dom" id="Dom" value="<?php echo $datos[0]["Dom"];?>" type="text" class="input large"  />           
            </p>
            <p>
            <label>Codigo Postal</label>
            <input name="Cp" id="Cp" value="<?php echo $datos[0]["Cp"];?>" type="text" class="input medium"  />
            </p>
            <p><label>Localidad</label>
            <input name="Loc" id="Loc" value="<?php echo $datos[0]["Loc"];?>" type="text" class="input medium" />
            </p>
            <p><label>Provincia</label>
            <input name="Prov" id="Prov" value="<?php echo $datos[0]["Nombre"];?>" type="text" class="input medium" />
            </p>          
            <p><label>Telefono</label>
            <input name="Tel" id="Tel" value="<?php echo $datos[0]["Tel"];?>" type="text" class="input medium" />
            </p>           
            <p>            
            <label>Observaciones</label>
            <textarea name="Observaciones" cols="50" rows="6" class="styled_textarea wysiwyg"><?php echo $datos[0]["Observaciones"];?></textarea>
            </p>
            <input type="hidden" name="id" value="<?php echo $datos[0]["idDeposito"];?>" />
            <input type="hidden" name="grabar" value="si" />            
            <input type="submit" class="button" value="Guardar" title="Guardar cambios" />
            </p>
            </form>

