	 <?php
    if(isset($_GET["st"]))
    {
    	switch ($_GET["st"])
    	{
    		case '1':
    			?>
    			<div class="fail large png_bg">Complete todos los campos obligatorios por favor.</div>
    			<?php
    		break;
            
    		case '2':
    			?>
    			<div class="success large png_bg">El registro se ha creado exitosamente.</div>
    			<?php
    		break;
            case '3':
    			?>
    			<div class="fail large png_bg">Error, Registro no creado.</div>
    			<?php
    		break;			
			case '4':
    			?>
    			<div class="fail large png_bg">Error, el Codigo ya existe, el registro no fue creado.</div>
    			<?php
    		break;
    		
    	}
    }
	?>

<h2>Nuevo Documento</h2>
<div style="float:left;width:70%;min-height: 120px;">

    <div class="form-inline">
        <label for="selTipodoc">Tipo</label>    
        <?php echo $selTipodoc; ?>
    
        <input id='letra' name='letra' type="text" disabled="disabled" value="" class="input" size="2" >
        <input id='puntoVenta' name='puntoVenta' type="text" disabled="disabled" value="" class="input" size="5" >
        <input id='idDoc' name='idDoc' type="text" disabled="disabled" value="" class="input" size="8" >
    </div>
    
    <div class="form-group">
        <div class="form-group">
            <label for="cliNom" class="col-sm-2 control-label">Cliente</label> 
            <div class="col-sm-10">
                <input id='cliNom' name='cliNom' type="text" title="razon social de cliente" class="input-medium form-control" ><a href="#" id="cli_masdatos">...mas datos</a>
                <input id='idCliente' name='idCliente' type="hidden" >   
            </div>
        </div>
        
        <div id="cli_contmasdatos" style="background-color: #FFFBCC" class="form-horizontal" >
            <div class="form-group">
                <label for="cliDom" class="col-sm-2 control-label">Domicilio</label>
                <div class="col-sm-10">
                  <input type="text" class="form-control" id="cliDom" name="cliDom" placeholder="Domicilio fiscal">
                </div>
            
                <label for="cliLoc" class="col-sm-2 control-label">Localidad</label>
                <div class="col-sm-10">
                  <input type="text" class="form-control input-medium" id="cliLoc" name="cliLoc" placeholder="Localidad">
                </div>
                
                <label for="cliLoc" class="col-sm-2 control-label">Localidad</label>
                <div class="col-sm-10"><input id='cliLoc' name='cliLoc' type="text" title="Localidad" class="input-medium form-control" ></div>
                
                <label for="cliCp" class="col-sm-2 control-label">Codigo postal</label>
                <div class="col-sm-10"><input id='cliCp' name='cliCp' type="text" title="Codigo Postal" class="input-small form-control" ></div>
                
                <label for="cliProv" class="col-sm-2 control-label">Provincia</label>
                <div class="col-sm-10"><input id='cliProv' name='cliProv' type="text" title="Provincia" class="input-small form-control" ></div>
                <label for="cliTel" class="col-sm-2 control-label">Telefono</label>
                <div class="col-sm-10"><input id='cliTel' name='cliTel' type="text" title="Telefono" class="input-medium form-control" ></div>
                
                <label for="cliMail" class="col-sm-2 control-label">Email</label>
                <div class="col-sm-10"><input id='cliMail' name='cliMail' type="Email" title="Email" class="input-medium form-control" ></div>            

            </div>       
        </div>

        <label for="cliCuit" class="col-sm-2 control-label">Cuit</label>
        <div class="col-sm-10"><input id='cliCuit' name='cliCuit' type="text" title="Cuit" class="input-small form-control" ></div>

        <label for="selcondfiscal" class="col-sm-2 control-label">Condicion fiscal</label>
        <div class="col-sm-10"><?php echo $selcondfiscal; ?></div>
    </div>

</div><!-- end div -->

<div style="float:left;width:30%;min-height: 120px;" class="form-horizontal">    

    <label for="fecha" class="col-sm-2 control-label">Fecha</label>    
    <div class="col-sm-10"><input id='fecha' name='fecha' type="text" title="Selecciona fecha de emision" class="input-small form-control" ></div>
    
    <label for="selMon" class="col-sm-2 control-label">Moneda</label>
    <div class="col-sm-10"><?php echo $selMon; ?></div>

    <label for="seldep" class="col-sm-2 control-label">Deposito</label>
    <div class="col-sm-10"><?php echo $seldep; ?></div>    
    
    <label for="sellista" class="col-sm-2 control-label">Lista</label>
    <div class="col-sm-10"><?php echo $sellista; ?></div>

</div><!-- end div -->
<div id="contenedor"></div>
<div style="width:100%;height:150px;float: left;">
<table class="TablaInterna" width="100%"> 
    <thead>
        <tr>
            <th width="10%">Codigo</th>
            <th width="8%">Cantidad</th>
            <th width="40%">Descripcion</th>
            <th width="8%">Descuento</th>
            <th width="8%">Precio</th>
            <th width="8%">Total</th>
            <th width="10%">Serie</th>
            <th width="10%">Accion</th>
        </tr>
        <tr>
            <th><input type="text" placeholder="Codigo o barcode" value="" name="txtCodigo" id="txtCodigo" class="input-small ingreso_item form-control" ></th>
            <th><input type="text" placeholder="Cantidad" value="1" name="txtCantidad" id="txtCantidad" class="input-small form-control ingreso_item" ></th>
            <th width="30%"><div class="ui-widget">
            <form id="frmBuscar">
                <input type="text" placeholder="descripcion o texto a buscar" value="" name="txtNombre" id="txtNombre" class="input-large form-control  ingreso_item" >
                <input type="hidden" id="func" name="func" value="cod" >
            </form></div></th>
            <th><input type="text" placeholder="Descuento" value="0.00" name="txtDescuento" id="txtDescuento" class="input-small form-control ingreso_item" ></th>
            <th><input type="text" placeholder="Precio" value="0.00" name="txtPrecio" id="txtPrecio" class="input-small form-control ingreso_item" ></th>
            <th><input type="text" placeholder="Total" value="0.00" name="txtTotal" id="txtTotal" class="input-small form-control ingreso_item" ></th>
            <th><input type="text" placeholder="Serie" value="" name="txtSerie" id="txtSerie" class="input-medium form-control ingreso_item"></th>
            <th><input type="button" value="+" name="btnAdd" title="Agregar item" id="btnAdd" class="button">
                <input type="button" value="x" name="btnClr" title="Limpiar ingreso" id="btnClr" class="button">
            </th>
        </tr>   
    </thead>
    <tbody>
        <tr>
            <td>1</td>      
            <td>1</td>
            <td>1</td>
            <td>1</td>
            <td>1</td>
            <td>1</td>
            <td><input id='serie' name='serie' type="text" title="Ingresar numero de serie" class="input full" ></td>
            <td><a href="#" class="del_item"><img src="<?php echo PATH_IMG ?>b_drop.png" title="Eliminar item"/></a>
                <a href="#" class="edit_item"><img src="<?php echo PATH_IMG ?>b_edit.png" title="Editar item"/></a>
            </td>
        </tr> 
    </tbody>
    <tfoot>
        <tr>
            <td>Items:</td>      
            <td><input type="text" title="cantidad de items" value="0" name="txtItems" id="txtItems" class="input" size="2" disabled="disabled"></td>
            <td>Unidades:<input type="text" title="cantidad de unidades" value="0" name="txtUnidades" id="txtUnidades" class="input" size="2" disabled="disabled"></td>
            <td></td>            
            <td>Subtotal</td>
            <td><input type="text" title="cantidad de unidades" value="0.00" name="txtSubTotal" id="txtSubTotal" class="input full"  disabled="disabled"></td> 
        </tr>  
        <tr>
            <td colspan="4"></td>                              
            <td>Saldo</td>
            <td><input type="text" title="cantidad de unidades" value="0.00" name="txtSaldo" id="txtSaldo" class="input full"  disabled="disabled"></td> 
        </tr> 
        <tr>
            <td colspan="4"></td>                              
            <td>Total</td>
            <td>0</td> 
        </tr> 
    </tfoot>
</table>
<input type="hidden" name="base_path" id="base_path" value="<?php echo BASE_URL;?>" >    
<input type="hidden" name="path_js" id="path_js" value="<?php echo PATH_JS;?>" >    
</div>