	 
        <h2>Listado de entidades</h2>

              <?php
    if(isset($_GET['st']))
        mensaje( $_GET['st'] );    
	?>
	<div class="row">
		<div class="form-group">
			<label for="idEntidadTipo">Tipo de entidad</label>
			<?php echo $seltipo; ?>
		</div>

	</div>
	<hr>
	<div class="row" >
        <a href="<?php echo BASE_URL;?>?accion=ent-add" id="ent-add" class="btn btn-primary" title="Nueva entidad"><span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Agregar Entidad</a>
    </div>
    
    <table id="tabla" class="tablesorter">
        <thead>          	
        <tr  style="font-weight: bold;">
	        <th align="center">ID</th>
	        <th align="center">Nombre</th>
	        <th align="center">Estado</th>       
	        <th align="center">Editar</th>        
        </tr>
        </thead>
        <tbody id="tablebody">
        
        </tbody>
     </table>
     
     <script type="text/javascript" defer="defer">
    	$(document).ready(function(){ 
            $("#tabla").tablesorter({
                        theme : 'blue',
                        widgets: ["zebra"],
                        headers : { 5 : { sorter: false }, 6 : { sorter: false } }
            });
        	actualizarTabla();

        	$("body").on( "change" , "#idEntidadTipo" , function(){
        		   actualizarTabla();    			
        	});

        } 
    	);

    	var actualizarTabla = function(){
    			var formData = new FormData();	
				formData.append("idEntidadTipo", $("#idEntidadTipo").val() );
				
				$.ajax({
					url: 'ajax.php?mode=ent-list',  
					type: 'POST',										
					data: formData,					
					cache: false,
					contentType: false,
					processData: false,
					//mientras enviamos el archivo
					beforeSend: function(){
												
					},
					//una vez finalizado correctamente
					success: function(data){												
											
						$("#tablebody").html(data);
						
					},
					//si ha ocurrido un error
					error: function(){
						
						$("#tablebody").html("sin resultados.");
					}
				});	 
    	} 
    </script>     