<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"><head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<link rel="shortcut icon" href="<?php echo Conectar::ruta();?>public/images/favicon.ico">
<title>..:: Intranet  - Agregar Usuarios ::..</title>
<!-- MASTER STYLESHEET-->
<link href="<?php echo Conectar::ruta();?>public/css/styles.css" rel="stylesheet" type="text/css" />

<!-- LOAD JQUERY -->
<script type="text/javascript" src="<?php echo Conectar::ruta();?>public/js/jquery.js" language="javascript"></script>

<!-- CUSTOM JQUERY AND FEATURES LOADER-->
<script src="<?php echo Conectar::ruta();?>public/js/scripts.js" type="text/javascript"></script>

<!-- LOAD TABLESORTER -->
<script type="text/javascript" src="<?php echo Conectar::ruta();?>public/js/jquery.tablesorter.min.js"></script>
<script type="text/javascript" src="<?php echo Conectar::ruta();?>public/js/jquery.tablesorter.pager.js"></script>

<!-- LOAD WYSIWYG EDITOR -->
<script type="text/javascript" src="<?php echo Conectar::ruta();?>public/js/jquery.wysiwyg.js"></script>
<link href="<?php echo Conectar::ruta();?>public/css/jquery.wysiwyg.css" rel="stylesheet" type="text/css" />

<!-- LOAD FACEBOX -->
<script type="text/javascript" src="<?php echo Conectar::ruta();?>public/js/facebox.js"></script>
<link href="<?php echo Conectar::ruta();?>public/css/facebox.css" rel="stylesheet" type="text/css" />
   
<script language="javascript" type="text/javascript" src="<?php echo Conectar::ruta();?>public/js/funciones.js"></script>   
    
<!--[if IE 6]>
<script src="<?php echo Conectar::ruta();?>public/js/pngfix.js"></script>
<script>
    DD_belatedPNG.fix('.png_bg');
</script>        
<![endif]-->


</head>

<body onload="muestraReloj();">


<!--  START HEADER -->
<div id="header">

	<!--  START HEAD_WRAP -->
  <?php include("header.phtml");?>
  <!--  END HEAD_WRAP -->
   
</div><!--  end div #header -->
<!--  END HEADER -->

	
    
    <!--  START CONTENT WRAPPER -->
    <div id="content_wrapper">
      <!--  START PRIMARY CONTENT -->
      <div id="primary_content">
	 
        <h2>Agregar Usuarios  </h2>
    <form action="" method="get">
            <p>
            <label>Small Form Field</label>
            <input name="textfield1" type="text" class="input small" id="textfield1" value="Small..."/>
            </p>
            <p>
            <label>Medium Form Field</label>
            <input name="textfield2" type="text" class="input medium" id="textfield2" value="Medium..." />
            </p>
            <p>
            <label>Large Form Field</label>
            <input name="textfield3" type="text" class="input large" id="textfield3" value="Large..." />
            </p>
            <p>
            <label>Check Boxes</label>
            </p>
            
            <p>
    <input name="check1" type="checkbox" class="checkbox" id="check1" />        
    This is a checkbox </p>
            
            <p>
              <input name="check2" type="checkbox" class="checkbox" id="check2" checked="checked" />
              This is another checkbox </p>
            <p>
            <label>Radio Buttons</label>
            <input name="radio" type="radio" class="radio" id="radio1" value="radio1" />
            This is a radio option </p>
             <p>
               <input name="radio" type="radio" class="radio" id="radio2" value="radio1" />
               Another Radio Option</p>
             <p>
               <input name="radio" type="radio" class="radio" id="radio3" value="radio3" />
               Last Radio Option </p>
             <p>
            <label>Drop Down (Combo) List</label>
             <select name="combo" class="select input">
               <option value="Option 1">Option 1</option>
               <option value="Option 2">Option 2</option>
               <option value="Option 3">Option 3</option>
               <option value="Option 4">Option 4</option>
               <option value="Option 5">Option 5</option>
             </select>
             </p>
            
            
            <p>
            <label>This is a text area...</label>
            <textarea name="textarea" cols="50" rows="7" class="styled_textarea wysiwyg">Text area for lots of lines of text...</textarea>
            </p>
            <p>
            <input type="button" class="button" value="Submit" />
            </p>
            </form>

      
	
	
      </div>
      <!--  END PRIMARY CONTENT -->

      
       <!--  START SIDEBAR -->
      <?php include("sidebar.phtml");?>
	  <!--  end div #sidebar -->
      <!--  END SIDEBAR -->
      
    </div><!--  end div #content_wrapper -->
<!--  END CONTENT_WRAPPER -->

<!--  START FOOTER -->
	<div id="footer">
    <p>
	<?php include("footer.phtml");?>
	</p>
</div>
<!--  END CEND -->
</body>
</html>

