<div id="head_wrap">
	
	<!--  START LOGO -->
    <!-- coment div
	<div id="logo"><h4 style="color:#FFFFFF">
	 <a href="<?php echo BASE_URL;?>?index=home" title="Intranet">
	<img src="<?php echo PATH_IMG;?>logods.png" border="0" /> 
	</a>
	</h4></div> -->
    <!--  END LOGO  -->
	
	<!--  START LOGIN -->
    <div id="login">
    <!-- MODAL LINK - POINT THIS LINK TO YOUR EXTERNAL HTML FILE AND AMEND THE HEIGHT/WIDTH ACCORDINGLY -->
    <p>Bienvenido (a) <span class="highlight"> <?php echo $_SESSION["user_login"];?></span>

	&nbsp;&nbsp;||&nbsp;&nbsp;
	<span id="spanreloj" class="highlight"></span>
	&nbsp;&nbsp;||&nbsp;&nbsp;
	<span class="highlight"><?php echo Conectar::fecha();?></span>
	&nbsp;&nbsp;||&nbsp;&nbsp;
	<a href="<?php echo BASE_URL;?>?accion=logout" style="text-decoration:none;" title="Cerrar mi Sesi&oacute;n"><span class="highlight">Cerrar mi sesión</span></a>
	</div>
    <!--  END LOGO  -->	
	
    <!--  START NAVIGATION -->    
       <?php require_once("menu.phtml");?> 
    <!--  END NAVIGATION -->
    
  </div><!--  end div #head_wrap -->