<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

<title><?php echo APP_NAME; ?></title>

<link href="<?php echo PATH_CSS; ?>bootstrap.min.css" rel="stylesheet">
<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="<?php echo PATH_JS; ?>jquery.min.js"></script>
<!-- Include all compiled plugins (below), or include individual files as needed -->
<script src="<?php echo PATH_JS; ?>bootstrap.min.js"></script>
<script language="javascript" type="text/javascript" src="<?php echo PATH_JS; ?>funciones.js"></script>

</head>

<body onload="document.form.reset();document.form.login.focus();">

<!-- START ADMIN WRAPPER -->
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-8 col-md-6" style="margin: 0 auto;float:none;">
      <center>
      <div class="panel panel-primary" style="margin-top:60px;">
        <div class="panel-heading">
          <h3 class="panel-title"><?php echo APP_NAME; ?></h3>
        </div>
        <div class="panel-body">
          <form action="" method="post" name="form" id="form" >
            <div class="form-group">
              <label for="login" class="sr-only control-label">Login</label>
              <div class="input-group">
                <div class="input-group-addon">Login</div>
                <input type="text" class="form-control selTxt" id="login" name="login" placeholder="Introduce el usuario">
              </div>
            </div>
            <div class="form-group">
              <label for="pass" class="sr-only control-label">Password</label>
              <div class="input-group">
                <div class="input-group-addon">Pass</div>
                <input type="password" class="form-control selTxt" id="pass" name="pass" placeholder="Introduce el password">
              </div>
            </div>
            <div class="form-group">
              <input type="hidden" name="grabar" value="si" />
              <input type="button" value="Entrar" id="btnEntrar" class="btn btn-primary"  />
              <input type="button"  value="Limpiar" class="btn btn-default" onclick="window.location='<?php echo BASE_URL;?>?accion=index';" />
            </div>
            <!--<div class="success large png_bg">This is a success message.</div>
            <div class="fail large png_bg">This is a failure message.</div>
            <div class="attention large png_bg">This is an attention message.</div>-->
          </form>
        </div>
        <div class="panel-footer">
            <div id="valor" class="alert alert-warning"><strong></strong></div>
          <?php

                if(isset($_GET["st"]))
                {
                  switch ($_GET["st"])
                  {
                    case '1':
                      ?>
                      <div class="alert alert-danger" role="alert"><strong>Los datos ingresados no son correctos.</strong></div>
                      <?php
                    break;

                    case '2':
                      ?>
                      <div class="alert alert-danger" role="alert"><strong>Debe estar logueado para ver este contenido.</strong></div>
                      <?php
                    break;
                    case '3':
                      ?>
                      <div class="alert alert-success" role="alert"><strong>Ha cerrado su sesión correctamente.</strong></div>
                      <?php
                        break;
                    case '4':
                      ?>
                      <div class="alert alert-danger" role="alert"><strong>Este Usuario se encuentra Inactivo, comunicate con el Administrador.</strong></div>
                      <?php
                    break;
                  case '5':
                      ?>
                      <div class="alert alert-danger" role="alert"><strong>Este Usuario no posee permisos de Administrador.</strong></div>
                      <?php
                    break;
                  }
                }
              ?>

        </div>
      </div>
    <!-- END ADMIN WRAPPER -->
      </center>
    </div><!-- END col -->
  </div><!-- END ROW -->
</div><!-- END container -->
</body>
</html>
