	<?php 
    if( isset($_GET['st']) ) mensaje( $_GET['st'] ); 
    ?>
    <div class="row">
                <a href="<?php echo BASE_URL;?>?accion=mon"> <span class="btn btn-success glyphicon glyphicon-arrow-left" aria-hidden="true"></span> </a>
    </div>
    <div class="row">
        <div class="col-md-12">
            <h2>Agregar Moneda</h2>
            <hr>
            <form action="" method="post" name="form" id="form">
                    

                    <div class="form-group validar">
                        <label for="Nombre" >Nombre (*)</label>
                        <input name="Nombre" id="Nombre" maxlenght="50" minlength="2"  type="text" class="form-control input-medium required"  />
                    </div>
                    
                    <div class="form-group validar">
                        <label for="Cambio">Cambio (equivalente a 1 unidad de la moneda principal) (*)</label>
                        <input name="Cambio" id="Cambio" type="text" greaterThan="0" class="form-control input-small required number" value="0.00" />
                    </div>
                    <div class="form-group validar">
                        <label>Simbolo(*)</label>
                        <input name="Simbolo" id="Simbolo" type="text" class="form-control input-small required"  />
                    </div>
                    <div class="checkbox">
                        <label>
                            <input type="checkbox"  value="1" checked="checked" name="Habilitada" id="Habilitada" />Habilitada
                        </label>
                    </div>   
                    
                    <div class="checkbox">
                            <label>  
                                <input type="checkbox"  title="hacer que esta moneda sea la principal de sistema" value="1" name="Principal" id="Principal" />Moneda Principal 
                            </label>   
                    </div>
                    <div class="checkbox">
                            <label> 
                                <input type="checkbox"  value="1" title="hacer que esta moneda sea la principal de la frontend web" name="Web" id="Web" />Moneda Principal en la Web
                            </label>                    
                    </div>
                   
                    <hr>
                    <div class="row">
                        <div class="col-md-12">
                            <input type="hidden" name="grabar" value="si" />            
                            <input type="submit" class="btn btn-default pull-right" value="Crear" title="Crear Nueva Moneda" />
                        </div>
                    </div>
                    
            </form>
        </div>
    </div>
