	 
        <h2>Monedas</h2>
              <?php
    if(isset($_GET["st"]))
    {
    	switch ($_GET["st"])
    	{
    		case '1':
    			?>
    			<div class="fail large png_bg">Esta Moneda no pudo ser eliminada.</div>
    			<?php
    		break;
            
    		case '2':
    			?>
    			<div class="success large png_bg">La Moneda se eliminó exitosamente.</div>
    			<?php
    		break;
    		
    	}
    }
	?>
	<table>
    <tr>
		<td valign="middle" align="left" colspan="10">
		Agregar Moneda
		<a href="<?php echo BASE_URL;?>?accion=mon-add" title="Nueva Moneda"><img src="<?php echo PATH_IMG;?>add_32.png" border="0" width="16" height="16" /></a>
		
		</td>
	</tr>
    </table>  
    <table id="tabla" class="tablesorter">
        <thead>          	
        <tr  style="font-weight: bold;">
        <th align="center">ID</th>
        <th align="center">Nombre</th>
        <th align="center">Cambio</th>
        <th align="center">Habilitada</th>
        <th align="center">Principal</th>
        
        <th align="center">Editar</th>
        <th align="center">Eliminar</th>
        </tr>
        </thead>
        <tbody>
        <?php
        for($i=0;$i<sizeof($datos);$i++)
        {
        ?>
         <tr>
        <td align="center"><?php echo $datos[$i]["idMoneda"];?></td>
        <td align="center"><?php echo $datos[$i]["Nombre"];?></td>
        <td align="center"><?php echo $datos[$i]["Cambio"];?></td>
        <td align="center"><?php echo ($datos[$i]["Habilitada"]==1)? "SI":"NO";?></td>
        <td align="center"><?php echo ($datos[$i]["Principal"]==1)? "SI":"NO";?></td>
        
        <td align="center"><a href="<?php echo BASE_URL;?>?accion=mon-edit&id=<?php echo $datos[$i]["idMoneda"];?>" title="Editar <?php echo $datos[$i]["Nombre"];?>"><img src="<?php echo PATH_IMG;?>b_edit.png" border="0" width="16" height="16"></a></td>
        <td align="center"><a href="javascript:void(0);" title="Eliminar <?php echo $datos[$i]["Nombre"];?>" onclick="eliminar('<?php echo BASE_URL;?>?accion=mon-del&id=<?php echo $datos[$i]["idMoneda"];?>')" ><img src="<?php echo PATH_IMG;?>b_drop.png" border="0" width="16" height="16"></a></td>
        </tr>
        <?php
        }
        ?>
        </tbody>
     </table>
     
     <script type="text/javascript" defer="defer">
    	$(document).ready(function() 
        { 
            $("#tabla").tablesorter({
                        theme : 'blue',
                        widgets: ["zebra"],
                        headers : { 5 : { sorter: false }, 6 : { sorter: false } }
            });
        } 
    	); 
    </script>     
