
<div class="container-fluid">
	<?php
	if(isset($_GET['st'])){
    	if($_GET['st'] == MSG_INFO) {
    		mensaje( MSG_INFO, "El Registro no se encontro, no se completo la operacion.");
    	}else
    		mensaje( $_GET['st']);
    }

	echo $ruta;
	?>
	<div style="height:40px;width:50%;float:left">
	<p style="float:left;"><a href="<?php echo $Regreso; ?>"><img src="<?php echo PATH_IMG;?>arrow_left_32.png" border="0" width="24" height="24" title="Pagina Anterior"></a></p></div>
	<div style="height:40px;width:50%;float:right"><p style="float:right;">
		<a href="#" class="btn btn-danger" name="imgEliminar" id="imgEliminar"><span class="glyphicon glyphicon-remove" aria-hidden="true"></a>
		<a href="#" class="btn btn-success" name="imgRecargar" id="imgRecargar"><span class="glyphicon glyphicon-refresh" aria-hidden="true"></a>
		<a href="#" class="btn btn-success" name="imgCopiar" id="imgCopiar"><span class="glyphicon glyphicon-copy" aria-hidden="true"></a>
	</div>

	<form action="" method="post" name="form" id="form">
	<div class="row">

		<div class="col-md-12 text-right">
			<input type="button" class="btn btn-default" value="Nuevo Producto Similar" name="BtnSimilar" id="BtnSimilar" title="crear un producto similar a otro de la misma categoria ahorra tiempo y evita errores" />
			<input type="button" class="btn btn-default" value=".Pdf" name="BtnPdf" id="BtnPdf" title="genera hoja pdf sobre producto" />
			<button type="submit" class="btn btn-primary" name="BtnGuardar" id="BtnGuardar" title="Guardar cambios" /><span class="glyphicon glyphicon-save" aria-hidden="true"></span> Guardar</button>
		</div>
		<hr>
		<div class="col-md-12">
			<?php echo $Titulo; ?>
		</div>

   	</div>
	<hr>

		<div class="row"> <!-- ROW1 -->
		   	<div class="col-md-6"><!-- COL1 -->
	   			<div class="panel panel-primary">
				  <div class="panel-heading">
				    <h3 class="panel-title">Descripcion de producto</h3>
				  </div>
				  <div class="panel-body">
				  		<div class="table-responsive">
					  		<table align="left" width="100%" class="table table-bordered">
								<tr>
									<td><strong >Nombre (*)</strong></td>
									<td><div class="validar"><input name="Nombre" id="Nombre" type="text" value="<?php echo $p[0]["Nombre"]; ?>" title="Es necesario asignar un nombre." class="form-control selTxt required" minlength="2" maxlength="250"  />
										<input name="SEO" id="SEO" type="hidden"  class="form-control"  /></div></td>
								</tr>
								<tr>
									<td><strong >Codigo (*)</strong></td>
									<td>
										<div class="input-group validar">
									      <span class="input-group-btn">
									        <button type="button" class="btn btn-success" id="buscarCodigo" title="Buscar codigo libre" /><span class="glyphicon glyphicon-search" aria-hidden="true"></span></button>
									      </span>
									      <input name="Codigo" id="Codigo" type="text" value="<?php echo $p[0]["Codigo"]; ?>" title="Es necesario asignar un codigo." class="form-control input-small selTxt required" minlength="4" maxlength="25" />
									    </div><!-- /input-group -->


										<img src="<?php echo PATH_IMG;?>accept.png" border="0"  id="aceptado">
										<img src="<?php echo PATH_IMG;?>loading.gif" border="0" width="24" height="24" id="cargando">
									</td>
								</tr>
								<tr>
									<td width="20%"><strong>Tipo de producto (*)</strong></td>
									<td width="80%"><div class="validar"><?php echo $seltipo; ?> <?php echo "(id:".$p[0]["idProducto"].")";?></div></td>
								</tr>
								<tr>
									<td><strong>Categoria (*)</strong></td>
									<td><div class="validar"><?php echo $selCat; ?></div></td>
								</tr>
								<tr>
									<td><strong >Barcode :</strong></td>
									<td><input name="CodBar" id="CodBar" type="text" value="<?php echo $p[0]["CodBar"]; ?>" title="codigo de barras" class="form-control input-medium"  /></td>
								</tr>
								<tr>
									<td><strong >Barcode2 :</strong></td>
									<td><input name="CodBar2" id="CodBar2" type="text" value="<?php echo $p[0]["CodBar2"]; ?>" title="codigo de barras" class="form-control input-medium"  /></td>
								</tr>
							</table>
						</div>
				  </div>
				</div><!-- end panel -->
	   		</div><!-- COL1 -->
	   		<div class="col-md-2"><!-- COL2 -->
	   				<div class="panel panel-primary">
					  <div class="panel-body">
					  		<div class="checkbox">
							  <label>
							    <input type="checkbox" class="checkbox" <?php if($p[0]["NotaEmerg"])echo 'checked="checked"';?>  title="Nota Emergente" name="NotaEmerg" id="NotaEmerg" />Nota Emergente
							  </label>
							  <label>
							    <input type="checkbox" class="checkbox" <?php if($p[0]["Publicar"])echo 'checked="checked"';?> title="Publicar" name="Publicar" id="Publicar" />Publicar
							  </label>
							  <label>
							    <input type="checkbox" class="checkbox" <?php if($p[0]["Destacado"])echo 'checked="checked"';?>  title="Destacado" name="Destacado" id="Destacado" />Destacado
							  </label>
							  <label>
							    <input type="checkbox" class="checkbox" <?php if($p[0]["Marcado"])echo 'checked="checked"';?> title="se marca un producto para ser utilizado en algun filtro" value="0" name="Marcado" id="Marcado" />
								Marcado
							  </label>
							  <label>
							    <input type="checkbox" class="checkbox" <?php if($p[0]["Usado"])echo 'checked="checked"';?> title="Usado" name="Usado" id="Usado" /> Usado
							  </label>
							  <label>
							    <input type="checkbox" class="checkbox" <?php if($p[0]["Reparable"])echo 'checked="checked"';?> title="para que figure en listados de productos reparables"  name="Reparable" id="Reparable" />
								Reparable
							  </label>
							  <label>
							    <input type="checkbox" class="checkbox" <?php if($p[0]["VenderSinStock"])echo 'checked="checked"';?> title="Vender sin stock"  name="VenderSinStock" id="VenderSinStock" />
								Vender sin stock
							  </label>
							  <label>
							    <input type="checkbox" class="checkbox" <?php if($p[0]["Promociones"])echo 'checked="checked"';?> title="habilitar promociones"  name="Promociones" id="Promociones" />
								Promociones
							  </label>
							  <label><input type="checkbox" class="checkbox" <?php if($p[0]["ImponerPrecio"])echo 'checked="checked"';?> title="Imponer precio si es un producto padre"  name="ImponerPrecio" id="ImponerPrecio" />
									Imponer Precio</label>
							  <label>
							    <input type="checkbox" class="checkbox" <?php if($p[0]["Habilitado"])echo 'checked="checked"';?> title="Habilitado"  name="Habilitado" id="Habilitado" />
								Habilitar
							  </label>
							</div>
					  </div>
					</div>
	   		</div><!-- COL2 -->
	   		<div class="col-md-4"><!-- COL3 -->
	   			<div class="panel panel-primary">
				  <div class="panel-body">
				    	<div class="row marketing center-block">
					    	<div class="btn-group-vertical" role="group">
										<input name="modelpath" id="modelpath" type="hidden" value="<?php echo MODEL_PATH;?>" />
										<input name="apppath" id="apppath" type="hidden" value="<?php echo APP_PATH;?>" />
										<input name="pathimg" id="pathimg" type="hidden" value="<?php echo PATH_IMG;?>" />
										<input name="pathjs" id="pathjs" type="hidden" value="<?php echo PATH_JS;?>" />

										<button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#divCargarImg" id="btnImagen" aria-label="Left Align" title="buscar una imagen" />
										  <span class="glyphicon glyphicon-search" aria-hidden="true"></span></button>

										<button type="button" class="btn btn-default btn-lg" id="clr
										" aria-label="Left Align">
										  <span class="glyphicon glyphicon-trash" aria-hidden="true"></span></button>
							</div>					   			
									<img src="<?php echo $imgpath;?>" id="imgImagen" style="max-height: 320px;" class="img-thumbnail img-responsive" title="<?php echo $imgpath; ?>">
									<input name="Imagen" id="Imagen" type="hidden" title="Imagen" value="<?php echo $p[0]["Imagen"]; ?>" />
						 </div>
				  </div>
				</div>
	   		</div><!-- COL3 -->
		</div> <!-- ROW1 -->
	<?php if( $ImponerPrecio == 0 ){  ?>
		<div class="row"><!-- ROW2 -->
			<div class="col-md-6"><!-- COL1 -->
				<div class="panel panel-primary" >
						  <div class="panel-heading">
						    <h3 class="panel-title">Modificar Precios</h3>
						  </div>
						  <div class="panel-body">
						    	<div class="table-responsive">
							    	<table width="60%" class="table table-bordered">
									  <tr>
										<td align="right">Moneda:</td>
										<td><div class="validar"><?php echo $selMon; ?></div></td>
									  </tr>
									  <tr>
										<td width="50%" align="right">Costo:</td>
										<td width="50%"><div class="validar"><input name="Costo" id="Costo" type="text" value="<?php echo $p[0]["Costo"]; ?>" title="Es necesario asignar un costo numerico valido." class="form-control selTxt required number"  /></div></td>
									  </tr>
									  <tr>
										<td align="right">Cantidad por defecto:</td>
										<td><div class="validar"><input name="UnidxDef" id="UnidxDef" type="text" value="<?php echo $p[0]["UnidxDef"]; ?>" title="Debes indicar cuantas unidades por defecto se calculan por cada producto." greaterThan="0" class="form-control selTxt required number form-control" /></div></td>
									  </tr>
									  <tr>
										<td align="right">Iva (*):</td>
										<td><div class="validar"><?php echo $seliva; ?></div></td>
									  </tr>
									  <tr>
										<td align="right">Max descuento:</td>
										<td><div class="validar"><input name="MaxDescuento" type="text" id="MaxDescuento" value="<?php echo $p[0]["MaxDescuento"]; ?>" size="8" maxlength="8" class="selTxt number form-control" /></div></td>
									  </tr>
									</table>
								</div>
						  </div>
				</div>
			</div><!-- COL1 -->
			<div class="col-md-6"><!-- COL2 -->
				<div class="panel panel-primary">
					  <div class="panel-heading">
					    <h3 class="panel-title">Listas de Precios</h3>
					  </div>
					  <div class="panel-body">
					    	<div class="table-responsive">
					    		<table width="80%"  class="table table-bordered">
								<tr>
									  <td width="15%">Lista</td>
									  <td width="15%">Costo C/Iva</td>
									  <td width="15%">Margen</td>
									  <td width="15%">Venta S/Iva</td>
									  <td width="15%">Venta C/Iva</td>
								</tr>
									<?php
									$resultados = sizeof($listas);
									for($i=0;$i<$resultados;$i++) { ?>
									  <tr>
										<td><?php echo $listas[$i]['Nombre']; ?></td>
										<td><input name="<?php echo "costo[".$listas[$i]['idLista'].']';?>" id="<?php echo "costo".$listas[$i]['idLista'];?>" idLista="<?php echo $listas[$i]['idLista']; ?>" type="text" value="0.00" size="8" maxlength="8" class="txtCosto" disabled />								</td>
										<td>
										<?php
										$proMargen=0;
										foreach ($proPrecios as $idl => $reg){
												if($reg["idLista"] == $listas[$i]['idLista']){
													$proMargen = $reg["Margen"];
												}
										}
										?>
										<div class="validar">
											<input name="<?php echo "margen[".$listas[$i]['idLista'].']';?>" id="<?php echo "margen".$listas[$i]['idLista'];?>" type="text" value="<?php echo $proMargen; ?>" size="8" maxlength="8" class="txtMargen selTxt required number form-control" />
										</div></td>
										<td>
										  	<div class="validar">
										  		<input name="<?php echo "precio[".$listas[$i]['idLista'].']';?>" id="<?php echo "precio".$listas[$i]['idLista'];?>" type="text" value="0.00" size="8" maxlength="8" class="txtPrecio selTxt number required form-control" />
										  	</div>
									    </td>
										<td><div class="validar">
												<input name="<?php echo "preciofinal[".$listas[$i]['idLista'].']';?>" id="<?php echo "preciofinal".$listas[$i]['idLista'];?>" type="text" value="0.00" size="8" maxlength="8" class="txtPrecioFinal selTxt number required form-control" />
											</div>
										</td>
									</tr>
									  <?php } ?>
							  </table>
						  	</div>
					  </div>
				</div>
			</div><!-- COL2 -->
		</div><!-- ROW2 -->
	<?php } ?>
		<div class="row"><!-- ROW3 -->
			<div class="col-md-6"><!-- COL1 -->
				<div class="panel panel-primary">
						  <div class="panel-heading">
						    <h3 class="panel-title">Modificar Stock</h3>
						  </div>
						  <div class="panel-body">
						    <div class="table-responsive">
						    	<table width="100%"  class="table table-bordered">
								<tr>
								  <td width="40%">Depositos</td>
								  <td width="20%">Stock</td>
								  <td width="20%">Min</td>
								  <td width="20%">Max</td>
								</tr>
								<?php
								$dep_totales = sizeof($depositos);
								for($i=0;$i<$dep_totales;$i++) { ?>
								  <tr>
									<?php
									$proStock_stock=0;
									$proStock_min=0;
									$proStock_max=0;
									foreach ($proStock as $ids => $reg){
											if($reg["idDeposito"] == $depositos[$i]['idDeposito']){
												$proStock_stock = $reg["StockCons"];
												$proStock_min = $reg["StockMin"];
												$proStock_max = $reg["StockMax"];
											}
									}
									?>
									<td><?php echo $depositos[$i]['idDeposito']; ?> - <?php echo $depositos[$i]['Nombre']; ?></td>
									<td><input name="<?php echo "stock[".$depositos[$i]['idDeposito'].']';?>" type="text" value="<?php echo $proStock_stock;?>" size="6" maxlength="6" class="selTxt" /></td>
									<td>
									  <input name="<?php echo "stockmin[".$depositos[$i]['idDeposito'].']';?>" type="text" id="stockmin" value="<?php echo $proStock_min;?>" size="5" maxlength="5" class="selTxt" /></td>
									<td><input name="<?php echo "stockmax[".$depositos[$i]['idDeposito'].']';?>" type="text" id="stockmax" value="<?php echo $proStock_max;?>" size="5" maxlength="5" class="selTxt" /></td>
								</tr>
								  <?php } ?>
							  </table>
						  	</div>
						  </div>
				</div>
			</div><!-- COL1 -->
			<div class="col-md-6"><!-- COL2 -->
				<div class="panel panel-primary">
						  <div class="panel-heading">
						    <h3 class="panel-title">Otras categorias asociadas</h3>
						  </div>
						  <div class="panel-body">
						  	<div class="table-responsive">
							    <table width="100%"  class="table table-bordered" id="tablacat">
									<thead>
									<tr>
										<td>
											<?php echo $selCat2; ?>
										</td>
										<td><button type="button" class="btn btn-primary" name="addCategoria" id="addCategoria" title="Agregar categoria" /><span class="glyphicon glyphicon-plus" aria-hidden="true"></span></button></td>
									</tr>
									</thead>
									<tbody>
									</tbody>
								</table>
							</div>
						  </div>
				</div>
			</div><!-- COL2 -->
		</div><!-- ROW3 -->
	<?php if( $idPadre <= 0  ){ ?>
		<div class="row"><!-- ROW4 -->
			<div class="col-md-12"><!-- COL1 -->
				<div class="panel panel-info">
						  <div class="panel-heading">
						    <h3 class="panel-title">Sub productos asociados</h3>
						  </div>
						  <div class="panel-body">
						  	<div class="table-responsive">
						  		<?php
								$sp_totales = sizeof($sp);
								echo '<br>Asociados: '.$sp_totales.'<br>'; 	?>
							    <table width="50%" class="table table-bordered" >
									<thead>
									<tr>
										<th width="60%"><strong>Descripcion</strong></th>

										<th width="40%"><strong>Accion</strong></th>
									</tr>
									</thead>
									<?php
										for($i=0;$i<$sp_totales;$i++) {
								  			echo '<tr><td><a href="'.BASE_URL.'?accion=pro-edit&id='.$sp[$i]['idProducto'].'">'.$sp[$i]['Nombre'].'</a></td>'.
								  			     '<td>
								  			     	<a href="'.BASE_URL.'?accion=pro-edit&id='.$sp[$i]['idProducto'].'" title="Editar Producto" class="btn btn-success"><span class="glyphicon glyphicon-cog" aria-hidden="true"></span></a>
								  			      </td></tr>' ;
								  	}
									?>
								</table>
								<a href="<?php echo BASE_URL.'?accion=pro-add&idpadre='.$p[0]['idProducto']; ?>" id="sub-pro-add" class="btn btn-success" title="Nuevo SubProducto"><span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Agregar Subproducto</a>
							</div>
						  </div>
				</div>
			</div><!-- COL1 -->
		</div><!-- ROW4 -->
	<?php } ?>
		<div class="row"><!-- ROW5 -->
			<div class="col-md-12"><!-- COL1 -->
				<div class="panel panel-primary">
						  <div class="panel-heading">
						    <h3 class="panel-title">Anotaciones</h3>
						  </div>
						  <div class="panel-body">
						  	<div class="table-responsive">
							    <table width="100%" class="table table-bordered" >
									<tr>
										<td><strong>Garantia (dias)</strong></td>
										<td><input name="Garantia" id="Garantia" value="<?php echo $p[0]["Garantia"]; ?>" type="text" title="Garantia" class="form-control" /></td>
									</tr>
									<tr valign="top">
										<td nowrap="nowrap" valign="top"><strong>Descripcion</strong></td>
										<td><textarea name="Descripcion" id="Descripcion"   title="Descripcion" cols="50" rows="6" class="form-control" /><?php echo $p[0]["Descripcion"]; ?></textarea></td>
									</tr>
									<tr valign="top">
										<td><strong>Nota</strong></td>
										<td><textarea name="Nota" id="Nota"  title="Nota" cols="50" rows="6" class="form-control" /><?php echo $p[0]["Nota"]; ?></textarea></td>
									</tr>
								</table>
							</div>
						  </div>
				</div>
			</div><!-- COL1 -->
		</div><!-- end ROW5 -->


			<div class="row">
				<div class="col-md-12 text-right">
				<div class="form-group">
					<input name="idProducto" id="idProducto" value="<?php echo $p[0]["idProducto"]; ?>" type="hidden"  class="form-control"  />
					<input name="idPadre" id="idPadre" value="<?php echo $p[0]["idPadre"]; ?>" type="hidden"  class="input medium"  />
					<input name="pDescuento" type="hidden" id="pDescuento" value="<?php echo $p[0]["pDescuento"]; ?>" size="8" maxlength="8" />
					<input name="idMarca" id="idMarca" value="<?php echo $p[0]["idMarca"]; ?>" type="hidden"  class="form-control"  />
					<input type="hidden" name="ImponerPrecio" id="ImponerPrecio" value="<?php echo $ImponerPrecio; ?>">
					<input type="hidden" name="grabar" value="si" />

					<input type="button" class="btn btn-default" value="Nuevo Producto Similar" name="BtnSimilar" id="BtnSimilar" title="crear un producto similar a otro de la misma categoria ahorra tiempo y evita errores" />
					<input type="button" class="btn btn-default" value=".Pdf" name="BtnPdf" id="BtnPdf" title="genera hoja pdf sobre producto" />
					<button type="submit" class="btn btn-primary" name="BtnGuardar" id="BtnGuardar" title="Guardar cambios" /><span class="glyphicon glyphicon-save" aria-hidden="true"></span> Guardar</button>
				</div>
				</div>
			</div>
            </form>
</div><!-- end CONTAINER -->
	<?php

require_once( PATH_JS . "upload/cargar_imagen.php");
	?>
