
  <script type="text/javascript">
        $(function() {
			$("#form").validity(function() {
                
                $("#Nombre").maxLength(250).minLength(2).require();
				$("#Codigo").maxLength(25).minLength(2).require();
                $("#idIva").match("number").greaterThan(0).require();
				$("#idMoneda").match("number").greaterThan(0).require();
				$("#idCategoria").match("number").greaterThan(0).require();
                
            });    
        });    
    </script>

	 <?php
    if(isset($_GET["st"]))
    {
    	switch ($_GET["st"])
    	{
    		case '1':
    			?>
    			<div class="fail large png_bg">Complete todos los campos obligatorios por favor.</div>
    			<?php
    		break;
            
    		case '2':
    			?>
    			<div class="success large png_bg">El registro se ha Guardado exitosamente.</div>
    			<?php
    		break;
            case '3':
    			?>
    			<div class="fail large png_bg">Error, Registro no Guardado.</div>
    			<?php
    		break;			
			case '4':
    			?>
    			<div class="fail large png_bg">Error, Registro no encontrado.</div>				
    			<?php 
    		break;
    		
    	}
    }?>
	<div style="height:40px;width:50%;float:left">
	<p style="float:left;"><a href="<?php echo BASE_URL;?>?accion=pro"><img src="<?php echo PATH_IMG;?>arrow_left_32.png" border="0" width="24" height="24" title="Pagina Anterior"></a></p></div>
	<div style="height:40px;width:50%;float:right"><p style="float:right;">
		<a href="#" name="imgEliminar" id="imgEliminar"><img src="<?php echo PATH_IMG;?>close_32.png" border="0" width="24" height="24" title="Eliminar Producto"></a>
		<a href="#" name="imgRecargar" id="imgRecargar"><img src="<?php echo PATH_IMG;?>refresh2_32.png" border="0" width="24" height="24"  title="Recargar Producto"></a>
		<a href="#" name="imgCopiar" id="imgCopiar"><img src="<?php echo PATH_IMG;?>copy_32.png" border="0" width="24" height="24"  title="Nuevo producto copiando este"></a>
		<a href="#" name="imgPdf" id="imgPdf"><img src="<?php echo PATH_IMG;?>pdf_32.png" border="0" width="24" height="24"  title="Generar pdf"></a>
		<a href="#" name="imgGuardar" id="imgGuardar"><img src="<?php echo PATH_IMG;?>save_32.png" border="0" width="24" height="24"  title="Guardar"></a></p>
	</div>
	<?php
    if(!empty($p)) 
    {
	?>
	
    <h2><?php echo $p[0]["Nombre"]." "; ?>(Editar) <?php if(!$p[0]["Habilitado"])echo ' /   (Deshabilitado)';?></h2>
        
    <form action="" method="post" name="form" id="form">
            	
			<div class="pro_columna1">			
			<div class="pro_titulo">
				
				<table align="left" width="100%" >
					<tr>
						<td width="20%"><strong>Tipo de producto (*)</strong></td>
						<td width="80%"><?php echo $seltipo; ?> <?php echo "(id:".$p[0]["idProducto"].")";?></td>						
					</tr>
					<tr>
						<td><strong>Categoria (*)</strong></td>
						<td><?php echo $selCat; ?></td>					
					</tr>
					<tr>
						<td><strong >Codigo (*)</strong></td>
						<td><input name="Codigo" id="Codigo" type="text" value="<?php echo $p[0]["Codigo"]; ?>" title="Codigo de producto" class="input short"  /><input type="button" class="button" value="Buscar Codigo" id="buscarCodigo" title="Buscar codigo libre" />   		
							<img src="<?php echo PATH_IMG;?>accept.png" border="0"  id="aceptado">
							<img src="<?php echo PATH_IMG;?>loading.gif" border="0" width="24" height="24" id="cargando">
						</td>
					</tr>
					<tr>
						<td><strong >Nombre (*)</strong></td>
						<td><input name="Nombre" id="Nombre" type="text" value="<?php echo $p[0]["Nombre"]; ?>" title="Nombre" class="input full"  />
							<input name="SEO" id="SEO" type="hidden"  class="input medium"  /></td>
					</tr>
					<tr>
						<td><strong >Barcode :</strong></td>
						<td><input name="CodBar" id="CodBar" type="text" value="<?php echo $p[0]["CodBar"]; ?>" title="codigo de barras" class="input short"  /></td>
					</tr>
					<tr>
						<td><strong >Barcode2 :</strong></td>
						<td><input name="CodBar2" id="CodBar2" type="text" value="<?php echo $p[0]["CodBar2"]; ?>" title="codigo de barras" class="input short"  /></td>
					</tr>
				</table>
			</div><!-- end pro_titulo -->
			<div class="pro_precios">    
						<p><strong>Modificar Precios</strong></p>
						<table width="60%" class="TablaInterna">
						  <tr>
							<td align="right">Moneda:</td>
							<td><?php echo $selMon; ?></td>
						  </tr>
						  <tr>
							<td width="50%" align="right">Costo:</td>
							<td width="50%"><input name="Costo" id="Costo" type="text" value="<?php echo $p[0]["Costo"]; ?>" title="moneda principal seleccionada por defecto" class="input short"  /></td>
						  </tr>
						  <tr>
							<td align="right">Cantidad por defecto:</td>
							<td><input name="UnidxDef" id="UnidxDef" type="text" value="<?php echo $p[0]["UnidxDef"]; ?>" title="cantidad de unidades por defecto" class="input short"  /></td>
						  </tr>
						  <tr>
							<td align="right">Iva (*):</td>
							<td><?php echo $seliva; ?></td>
						  </tr>
						  <tr>
							<td align="right">Max descuento:</td>
							<td><input name="MaxDescuento" type="text" id="MaxDescuento" value="<?php echo $p[0]["MaxDescuento"]; ?>" size="8" maxlength="8" /></td>
						  </tr>
						</table>
					<br />						
					
					<p><strong>Listas de Precios</strong> (en Moneda Principal)</p>	
					<table width="80%"  class="TablaInterna">
						<tr>
							  <td width="15%">Lista</td>
							  <td width="15%">Costo C/Iva</td>
							  <td width="15%">Margen</td>
							  <td width="15%">Venta S/Iva</td>
							  <td width="15%">Venta C/Iva</td>
						</tr>
							<?php 
							$resultados = sizeof($listas);
							for($i=0;$i<$resultados;$i++) { ?>
							  <tr>
								<td><?php echo $listas[$i]['Nombre']; ?></td>
								<td><input name="<?php echo "costo[".$listas[$i]['idLista'].']';?>" id="<?php echo "costo".$listas[$i]['idLista'];?>" type="text" value="0.00" size="8" maxlength="8" class="txtCosto" disabled />								</td>
								<td>
								<?php
								$proMargen=0;
								foreach ($proPrecios as $idl => $reg){ 										
										if($reg["idLista"] == $listas[$i]['idLista']){
											$proMargen = $reg["Margen"];
										}
								}
								?>
								<input name="<?php echo "margen[".$listas[$i]['idLista'].']';?>" id="<?php echo "margen".$listas[$i]['idLista'];?>" type="text" value="<?php echo $proMargen; ?>" size="8" maxlength="8" class="txtMargen" /></td>
								<td>  
								  <input name="<?php echo "precio[".$listas[$i]['idLista'].']';?>" id="<?php echo "precio".$listas[$i]['idLista'];?>" type="text" value="0.00" size="8" maxlength="8" class="txtPrecio" /></td>
								<td><input name="<?php echo "preciofinal[".$listas[$i]['idLista'].']';?>" id="<?php echo "preciofinal".$listas[$i]['idLista'];?>" type="text" value="0.00" size="8" maxlength="8" class="txtPrecioFinal" />
								</td>
							</tr>
							  <?php } ?>
					  </table>
					</div><!-- div pro_precios -->
					<div class="pro_descripcion">						
						<table width="100%" >							
							<tr>
								<td><strong>Garantia (dias)</strong></td>
								<td><input name="Garantia" id="Garantia" value="<?php echo $p[0]["Garantia"]; ?>" type="text" title="Garantia" class="input short" /></td>
							</tr>
							<tr valign="top">
								<td nowrap="nowrap" valign="top"><strong>Descripcion</strong></td>
								<td><textarea name="Descripcion" id="Descripcion"   title="Descripcion" cols="50" rows="6" class="styled_textarea wysiwyg" /><?php echo $p[0]["Descripcion"]; ?></textarea></td>
							</tr>
							<tr valign="top">
								<td><strong>Nota</strong></td>
								<td><textarea name="Nota" id="Nota"  title="Nota" cols="50" rows="6" class="styled_textarea wysiwyg" /><?php echo $p[0]["Nota"]; ?></textarea></td>
							</tr>
						</table>												
					</div><!-- end pro_descripcion-->
			</div><!-- end pro_columna -->
			<div class="pro_columna2">
				<div class="pro_imagen">
					<?php
					$imgpath = PATH_IMG."/NoDisponible.jpg";
					if(is_file(PATH_PUBLIC_RELAT.DIR_IMG.$imgdir."/".$p[0]["Imagen"])){
						$imgpath = PATH_PUBLIC_RELAT.DIR_IMG.$imgdir."/".$p[0]["Imagen"];
					}
					?>
					<img src="<?php echo $imgpath;?>" border="0" id="imgImagen" width="155" height="200" >
					<input name="modelpath" id="modelpath" type="hidden" value="<?php echo MODEL_PATH;?>" />
					<input name="apppath" id="apppath" type="hidden" value="<?php echo APP_PATH;?>" />
					<input name="pathimg" id="pathimg" type="hidden" value="<?php echo PATH_IMG;?>" />				
					<input name="pathjs" id="pathjs" type="hidden" value="<?php echo PATH_JS;?>" />
					<input name="Imagen" id="Imagen" type="hidden" title="Imagen" class="input medium"  />
					<input type="button" class="button" value="Agregar Imagen" id="btnImagen" title="buscar una imagen" />            
					<input type="button" class="button" value="Borrar" id="clrImagen" title="Borrar imagen" />   		         
				</div><!-- end pro_imagen -->													  
				<div class="pro_control">						
						<p><input type="checkbox" class="checkbox" <?php if($p[0]["NotaEmerg"])echo 'checked="checked"';?>  title="Nota Emergente" name="NotaEmerg" id="NotaEmerg" />Nota Emergente   </p>
						<p><input type="checkbox" class="checkbox" <?php if($p[0]["Publicar"])echo 'checked="checked"';?> title="Publicar" name="Publicar" id="Publicar" />Publicar  </p> 
						<p><input type="checkbox" class="checkbox" <?php if($p[0]["Destacado"])echo 'checked="checked"';?>  title="Destacado" name="Destacado" id="Destacado" />Destacado </p> 			
						<p><input type="checkbox" class="checkbox" <?php if($p[0]["Marcado"])echo 'checked="checked"';?> title="se marca un producto para ser utilizado en algun filtro" value="0" name="Marcado" id="Marcado" />
						Marcado </p>            
						<p><input type="checkbox" class="checkbox" <?php if($p[0]["Usado"])echo 'checked="checked"';?> title="Usado" name="Usado" id="Usado" /> Usado</p>
						<p><input type="checkbox" class="checkbox" <?php if($p[0]["Reparable"])echo 'checked="checked"';?> title="para que figure en listados de productos reparables"  name="Reparable" id="Reparable" />
						Reparable </p>
						<p><input type="checkbox" class="checkbox" <?php if($p[0]["VenderSinStock"])echo 'checked="checked"';?> title="Vender sin stock"  name="VenderSinStock" id="VenderSinStock" />
						Vender sin stock </p>
						<p><input type="checkbox" class="checkbox" <?php if($p[0]["Promociones"])echo 'checked="checked"';?> title="habilitar promociones"  name="Promociones" id="Promociones" />
						Promociones </p>
						<p><input type="checkbox" class="checkbox" <?php if($p[0]["Habilitado"])echo 'checked="checked"';?> title="Habilitado"  name="Habilitado" id="Habilitado" />
						Habilitar</p>						
				</div><!-- end pro_control -->				
				<div class="pro_stock">						
					  <p><strong>Modificar Stock</strong></p>
					  <table width="100%"  class="TablaInterna">
						<tr>
						  <td width="40%">Depositos</td>
						  <td width="20%">Stock</td>
						  <td width="20%">Min</td>
						  <td width="20%">Max</td>
						</tr>
						<?php 
						$dep_totales = sizeof($depositos);
						for($i=0;$i<$dep_totales;$i++) { ?>
						  <tr>
							<?php 							
							$proStock_stock=0;
							$proStock_min=0;
							$proStock_max=0;
							foreach ($proStock as $ids => $reg){ 										
									if($reg["idDeposito"] == $depositos[$i]['idDeposito']){
										$proStock_stock = $reg["Stock"];
										$proStock_min = $reg["StockMin"];
										$proStock_max = $reg["StockMax"];
									}
							}
							?>
							<td><?php echo $depositos[$i]['idDeposito']; ?> - <?php echo $depositos[$i]['Nombre']; ?></td>
							<td><input name="<?php echo "stock[".$depositos[$i]['idDeposito'].']';?>" type="text" value="<?php echo $proStock_stock;?>" size="6" maxlength="6" /></td>
							<td>
							  <input name="<?php echo "stockmin[".$depositos[$i]['idDeposito'].']';?>" type="text" id="stockmin" value="<?php echo $proStock_min;?>" size="5" maxlength="5" /></td>
							<td><input name="<?php echo "stockmax[".$depositos[$i]['idDeposito'].']';?>" type="text" id="stockmax" value="<?php echo $proStock_max;?>" size="5" maxlength="5" /></td>
						</tr>
						  <?php } ?>
					  </table>
				</div><!-- div producto_stock -->		
				<div class="pro_cat">
						<p><strong>Agregar otras categorias</strong></p>						
						<table width="100%"  class="TablaInterna" id="tablacat">							
							<thead>
							<tr>
								<td><?php echo $selCat2; ?><input type="button"  value="+" name="addCategoria" id="addCategoria" title="Agregar categoria" /></td>															
								<td>Accion</td>
							</tr>
							</thead>
							<tbody>							
							</tbody>
						</table>
				</div><!-- end pro_cat -->
			</div><!-- end pro_columna -->	
					
			<input name="idProducto" id="idProducto" value="<?php echo $p[0]["idProducto"]; ?>" type="hidden"  class="input medium"  />					
			<input name="pDescuento" type="hidden" id="pDescuento" value="<?php echo $p[0]["pDescuento"]; ?>" size="8" maxlength="8" />			
			<input name="idMarca" id="idMarca" value="<?php echo $p[0]["idMarca"]; ?>" type="hidden"  class="input medium"  />
			<input name="idPadre" id="idPadre" value="<?php echo $p[0]["idPadre"]; ?>" type="hidden"  class="input medium"  />					
			<input type="hidden" name="grabar" value="si" />            
			<div class="pro_submit">
				<input type="button" class="button" value="Nuevo Producto Similar" name="BtnSimilar" id="BtnSimilar" title="crear un producto similar a otro de la misma categoria ahorra tiempo y evita errores" />
				<input type="button" class="button" value=".Pdf" name="BtnPdf" id="BtnPdf" title="genera hoja pdf sobre producto" />
				<input type="submit" class="button" value="Guardar" name="BtnGuardar" id="BtnGuardar" title="Guardar cambios" /> 
			</div>
            </form>
	<?php } //if variable st!=4?>