<div class="container-fluid"><!-- CONTAINER -->
	<?php
	if(isset($_GET['st'])){
    	if($_GET['st'] == MSG_INFO) {
    		mensaje( MSG_INFO, "El Registro ya existe, no se completo la operacion.");
    	}else
    		mensaje( $_GET['st']);
    }
	echo $ruta;
	?>
	<div class="row">
	<p style="float:left;"><a href="<?php echo $retorno; ?>"><img src="<?php echo PATH_IMG;?>arrow_left_32.png" border="0" width="24" height="24" title="Pagina Anterior"></a></p>
	</div>

	<form action="" method="post" name="form" id="form">
    <div class="row">
    	<div class="col-md-6"><h2><?php echo ( $idPadre>0 )? $subp[0]['Nombre'].'('.$subp[0]['Codigo'].') -> Sub': 'Nuevo Producto'; ?></h2></div>
		<div class="col-md-6 text-right">
			<button type="submit" class="btn btn-primary"  name="BtnGuardar" id="BtnGuardar" title="Crear Nuevo Producto" /><span class="glyphicon glyphicon-save" aria-hidden="true"></span> Guardar</button>
		</div>
    	<hr>
   	</div>

    	<div class="row"><!-- ROW1 -->
    		<div class="col-xs-12 col-md-6"><!-- COL1 TITULO-->
				<div class="panel panel-primary">
				  	<div class="panel-heading">
				    	<h3 class="panel-title">Descripcion de producto</h3>
				  	</div>
					<div class="panel-body">
				  		<div class="table-responsive">
				  			<table align="left" width="100%" class="table table-bordered"><!-- Nombre Producto -->
								<tr>
									<td><strong >Nombre (*)</strong></td>
									<td><div class="validar">
											<input name="Nombre" id="Nombre" type="text" title="Debes escribir un nombre valido" class="form-control selTxt required" minlength="2" maxlength="250"  />
										</div>
										<input name="SEO" id="SEO" type="hidden"  class="input medium"  /></td>
								</tr>
								<tr>
									<td><div class="checkbox">
											<label><input id="chkSub" name="chkSub" type="checkbox" <?php if( $idPadre > 0 ) echo 'checked';  ?> ><strong> SubProducto de </strong></label>
									    </div>
									</td>
									<td><div class="input-group">
									      <span class="input-group-btn">
									        <button type="button" class="btn btn-success ctrlSubPro" id="buscarSub" name="buscarSub" title="Buscar padre" disabled="disabled"/><span class="glyphicon glyphicon-search" aria-hidden="true"></span></button>
									      </span>
									      <input name="txtpadre" id="txtpadre" type="text" title="descripcion de producto padre (F9)" class="form-control input-large" disabled="disabled" <?php if( $idPadre>0 )echo 'value="'.$subp[0]["Codigo"].', '.$subp[0]['Nombre'].'"'; ?> />
									    </div><!-- /input-group -->
										<input name="idPadre" id="idPadre" value="<?php echo $idPadre; ?>" type="text"  class="input medium"  />
									</td>
								</tr>
								<tr>
									<td><strong >Codigo (*)</strong></td>
									<td><div class="input-group validar">
									      <span class="input-group-btn">
									        <button type="button" class="btn btn-success" id="buscarCodigo" title="Buscar codigo libre" /><span class="glyphicon glyphicon-search" aria-hidden="true"></span></button>
									      </span>
									      <input name="Codigo" id="Codigo" type="text" title="Debes escribir un codigo valido" minlenght="4" maxlength="25"  class="form-control input-small selTxt required"  />
									    </div><!-- /input-group -->
										<img  border="0"  id="aceptado">
										<img src="<?php echo PATH_IMG;?>loading.gif" border="0" width="24" height="24" id="cargando">
									</td>
								</tr>
								<tr>
									<td width="20%"><strong>Tipo de producto (*)</strong></td>
									<td width="80%"><div class="validar"><?php echo $seltipo; ?></div></td>
								</tr>
								<tr>
									<td><strong>Categoria (*)</strong></td>
									<td><div class="validar"><?php echo $selCat; ?></div></td>
								</tr>
								<tr>
									<td><strong >Barcode :</strong></td>
									<td><input name="CodBar" id="CodBar" type="text" title="codigo de barras" class="form-control input-medium"  /></td>
								</tr>
								<tr>
									<td><strong >Barcode2 :</strong></td>
									<td><input name="CodBar2" id="CodBar2" type="text" title="codigo de barras" class="form-control input-medium"  /></td>
								</tr>
							</table>
				  		</div>
			  		</div>
		  		</div>
    		</div><!-- COL1 TITULO-->
    		<div class="col-xs-12 col-md-2"><!-- COL2 CHECKBOX -->
    				<div class="panel panel-primary">
						<div class="panel-body">
					  		<div class="checkbox">
					  				<label><input type="checkbox" class="checkbox" checked="checked"  title="Nota Emergente" name="NotaEmerg" id="NotaEmerg" />Nota Emergente   </label>
									<label><input type="checkbox" class="checkbox" checked="checked"  title="Publicar" name="Publicar" id="Publicar" />Publicar  </label>
									<label><input type="checkbox" class="checkbox"   title="Destacado" name="Destacado" id="Destacado" />Destacado </label>
									<label><input type="checkbox" class="checkbox" title="se marca un producto para ser utilizado en algun filtro" value="0" name="Marcado" id="Marcado" />
									Marcado </label>
									<label><input type="checkbox" class="checkbox" title="Usado" name="Usado" id="Usado" /> Usado</label>
									<label><input type="checkbox" class="checkbox" title="para que figure en listados de productos reparables"  name="Reparable" id="Reparable" />
									Reparable </label>
									<label><input type="checkbox" class="checkbox" checked="checked" title="Vender sin stock"  name="VenderSinStock" id="VenderSinStock" />
									Vender sin stock </label>
									<label><input type="checkbox" class="checkbox" checked="checked" title="habilitar promociones"  name="Promociones" id="Promociones" />
									Promociones </label>
									<label><input type="checkbox" class="checkbox"  title="Imponer precio si es un producto padre"  name="ImponerPrecio" id="ImponerPrecio" />
									Imponer Precio</label>
									<label><input type="checkbox" class="checkbox" checked="checked" title="Habilitado"  name="Habilitado" id="Habilitado" />
									Habilitar</label>
					  		</div>
				  		</div>
			  		</div>
    		</div> <!-- COL2 CHECKBOX-->
    		<div class="col-xs-12 col-md-4"><!-- COL3 IMAGEN-->
    				<div class="panel panel-primary">
						<div class="panel-body">
							<div class="row marketing center-block">
						  		<div class="btn-group-vertical" role="group">
									<input name="modelpath" id="modelpath" type="hidden" value="<?php echo MODEL_PATH;?>" />
									<input name="apppath" id="apppath" type="hidden" value="<?php echo APP_PATH;?>" />
									<input name="pathimg" id="pathimg" type="hidden" value="<?php echo PATH_IMG;?>" />
									<input name="pathjs" id="pathjs" type="hidden" value="<?php echo PATH_JS;?>" />
									<input name="Imagen" id="Imagen" type="hidden" title="Imagen" class="input medium"  />
									<button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#divCargarImg" id="btnImagen" aria-label="Left Align" title="buscar una imagen" />
										  <span class="glyphicon glyphicon-search" aria-hidden="true"></span></button>
									<button type="button" class="btn btn-default btn-lg" id="clrImagen" aria-label="Left Align">
										  <span class="glyphicon glyphicon-trash" aria-hidden="true"></span></button>
						  		</div>
						  		<img src="<?php echo PATH_IMG;?>255x320.png" border="0" id="imgImagen" style="max-height: 320px;" class="img-thumbnail img-responsive" >
					  		</div>
				  		</div>
			  		</div>
    		</div><!-- COL3 IMAGEN-->
    	</div><!-- ROW1 -->
	<?php if ( $ImponerPrecio <= 0 ){ ?>
    	<div class="row"><!-- ROW2 : precios -->
    		<div class="col-xs-12 col-md-6"><!-- COL1 -->
    			<div class="panel panel-primary">
				  	<div class="panel-heading">
				    	<h3 class="panel-title">Modificar Precios</h3>
				  	</div>
					<div class="panel-body">
				  		<div class="table-responsive">
							<table width="60%" class="table table-bordered">
							  <tr>
								<td align="right">Moneda:</td>
								<td><div class="validar"><?php echo $selMon; ?></div></td>
							  </tr>
							  <tr>
								<td width="50%" align="right">Costo:</td>
								<td width="50%"><div class="validar">
													<input name="Costo" id="Costo" type="text" value="0.00" title="Es necesar un costo al producto." class="form-control input-short required number selTxt"  />
												</div>
								</td>
							  </tr>
							  <tr>
								<td align="right">Cantidad por defecto:</td>
								<td><div class="validar">
										<input name="UnidxDef" id="UnidxDef" type="text" value="1" greaterThan="0" title="Debes indicar cuantas unidades por defecto se calculan por cada producto." class="selTxt form-control input-short required number" /></td>
									</div>
							  </tr>
							  <tr>
								<td align="right">Iva (*):</td>
								<td><div class="validar"><?php echo $seliva; ?></div></td>
							  </tr>
							  <tr>
								<td align="right">Max descuento:</td>
								<td><div class="validar"><input name="MaxDescuento" type="text" id="MaxDescuento" value="0.00" size="8" maxlength="8" class="selTxt number form-control" /></div></td>
							  </tr>
							</table>
				  		</div>
			  		</div>
		  		</div>
    		</div><!-- COL1 -->
    		<div class="col-xs-12 col-md-6"><!-- COL2 -->
    			<div class="panel panel-primary">
				  	<div class="panel-heading">
				    	<h3 class="panel-title"><strong>Listas de Precios</strong> (en Moneda Principal)</h3>
				  	</div>
					<div class="panel-body">
				  		<div class="table-responsive">
							<table width="80%"  class="table table-bordered">
								<tr>
									  <td width="15%">Lista</td>
									  <td width="15%">Costo C/Iva</td>
									  <td width="15%">Margen</td>
									  <td width="15%">Venta S/Iva</td>
									  <td width="15%">Venta C/Iva</td>
								</tr>
									<?php
									$resultados = sizeof($listas);
									for($i=0;$i<$resultados;$i++) { ?>
									  <tr>
										<td><?php echo $listas[$i]['Nombre']; ?></td>
										<td><input name="<?php echo "costo[".$listas[$i]['idLista'].']';?>" id="<?php echo "costo".$listas[$i]['idLista'];?>" idLista="<?php echo $listas[$i]['idLista']; ?>" type="text" value="0.00" size="8" maxlength="8" class="txtCosto form-control" disabled />								</td>
										<td><div class="validar"><input name="<?php echo "margen[".$listas[$i]['idLista'].']';?>" id="<?php echo "margen".$listas[$i]['idLista'];?>" type="text" value="<?php echo $listas[$i]['Margen']; ?>" size="8" maxlength="8" class="txtMargen number required form-control selTxt" /></div></td>
										<td>
										  <div class="validar"><input name="<?php echo "precio[".$listas[$i]['idLista'].']';?>" id="<?php echo "precio".$listas[$i]['idLista'];?>" type="text" value="0.00" size="8" maxlength="8" class="txtPrecio number required form-control selTxt" /></div></td>
										<td><div class="validar"><input name="<?php echo "preciofinal[".$listas[$i]['idLista'].']';?>" id="<?php echo "preciofinal".$listas[$i]['idLista'];?>" type="text" value="0.00" size="8" maxlength="8" class="txtPrecioFinal number required form-control selTxt" /></div>
										</td>
									</tr>
									  <?php } ?>
							  </table>
				  		</div>
			  		</div>
		  		</div>
    		</div><!-- COL2 -->
    	</div><!-- ROW2 -->
    <?php } ?>
    	<div class="row"><!-- ROW3 -->
    		<div class="col-md-6"><!-- COL1 -->
    			<div class="panel panel-primary">
				  	<div class="panel-heading">
				    	<h3 class="panel-title">Modificar Stock</h3>
				  	</div>
					<div class="panel-body">
				  		<div class="table-responsive">
				  			<table width="100%"  class="table table-bordered">
								<tr>
								  <td width="40%">Depositos</td>
								  <td width="20%">Stock</td>
								  <td width="20%">Min</td>
								  <td width="20%">Max</td>
								</tr>
								<?php
								$dep_totales = sizeof($depositos);
								for($i=0;$i<$dep_totales;$i++) { ?>
								  <tr>
									<td><?php echo $depositos[$i]['idDeposito']; ?> - <?php echo $depositos[$i]['Nombre']; ?></td>
									<td><input name="<?php echo "stock[".$depositos[$i]['idDeposito'].']';?>" type="text" value="0" size="6" maxlength="6" /></td>
									<td>
									  <input name="<?php echo "stockmin[".$depositos[$i]['idDeposito'].']';?>" type="text" id="stockmin" value="0" size="5" maxlength="5" /></td>
									<td><input name="<?php echo "stockmax[".$depositos[$i]['idDeposito'].']';?>" type="text" id="stockmax" value="0" size="5" maxlength="5" /></td>
								</tr>
								  <?php } ?>
							  </table>
				  		</div>
			  		</div>
		  		</div>

    		</div><!-- COL1 -->
    	<?php if ( $idPadre <= 0 ){ ?>
    		<div class="col-md-6"><!-- COL2 : otras categorias-->
    			<div class="panel panel-primary">
				  	<div class="panel-heading">
				    	<h3 class="panel-title">Agregar otras categorias</h3>
				  	</div>
					<div class="panel-body">
				  		<div class="table-responsive">
							<table width="100%"  class="table table-bordered" id="tablacat">
								<thead>
								<tr>
									<td><?php echo $selCat2; ?></td>
									<td><button type="button" class="btn btn-primary ctrlNoSubPro" name="addCategoria" id="addCategoria" title="Agregar categoria" /><span class="glyphicon glyphicon-plus" aria-hidden="true"></span></button></td>
								</tr>
								</thead>
								<tbody>
								</tbody>
							</table>
				  		</div>
			  		</div>
		  		</div>
    		</div><!-- COL2 -->
		<?php } ?>
    	</div><!-- ROW3 -->
    	<div class="row"><!-- ROW4 -->
    		<div class="col-md-12"><!-- COL1 -->
    			<div class="panel panel-primary">
				  	<div class="panel-heading">
				    	<h3 class="panel-title">Anotaciones</h3>
				  	</div>
					<div class="panel-body">
				  		<div class="table-responsive">
				  			<table width="100%" class="table table-bordered" >
								<tr>
									<td><strong>Garantia (dias)</strong></td>
									<td><input name="Garantia" id="Garantia" value="0" type="text" title="Garantia" class="input short" /></td>
								</tr>
								<tr valign="top">
									<td nowrap="nowrap" valign="top"><strong>Descripcion</strong></td>
									<td><textarea name="Descripcion" id="Descripcion"   title="Descripcion" cols="50" rows="6" class="styled_textarea wysiwyg" /></textarea></td>
								</tr>
								<tr valign="top">
									<td><strong>Nota</strong></td>
									<td><textarea name="Nota" id="Nota"  title="Nota" cols="50" rows="6" class="styled_textarea wysiwyg" /></textarea></td>
								</tr>
							</table>
				  		</div>
			  		</div>
		  		</div>
    		</div><!-- COL1 -->
    	</div><!-- ROW4 -->
    	<div class="row"><!-- ROW5 -->
    		<div class="col-md-12 text-right"><!-- COL1 -->
    			<div class="form-group">
	    			<input name="pDescuento" type="hidden" id="pDescuento" value="0" size="8" maxlength="8" />
					<input name="idMarca" id="idMarca" value="0" type="hidden"  class="input medium"  />
					<input type="hidden" name="retorno" value="<?php echo $retorno; ?>" />
					<input type="hidden" name="ImponerPrecio" id="ImponerPrecio" value="<?php echo $ImponerPrecio; ?>" />
					<input type="hidden" name="grabar" value="si" />
					<button type="submit" class="btn btn-primary" name="BtnGuardar" id="BtnGuardar" title="Crear Nuevo Producto" /><span class="glyphicon glyphicon-save" aria-hidden="true"></span> Guardar</button>
				</div>
    		</div><!-- COL1 -->
    	</div><!-- ROW5 -->

    </form>
</div><!-- CONTAINER -->
<?php require_once( PATH_JS . "upload/cargar_imagen.php"); 	?>
