<div id="sidebar">
      
        <h3>Avisos Importantes</h3>
        <ul>
          <li>
            <img src="<?php echo PATH_IMG;?>home_32.png" alt="Home" width="32" height="32" class="png_bg" /> <a href="#">Informacion 1</a><br />
            <p>Descripciones de Informacion 1.</p>
          </li>
          <li>
           <img src="<?php echo PATH_IMG;?>user_32.png" alt="Users" width="32" height="32" class="png_bg" /> <a href="#">Informacion 2</a><br />
           <p>Descripciones de Informacion 2.</p>
          </li>
          <li class="last">
            <img src="<?php echo PATH_IMG;?>chart_32.png" alt="Stats" width="32" height="32" class="png_bg" /> <a href="#">Informacion 3</a><br />
            <p>Descripciones de Informacion 3.</p>
          </li>
        </ul>
        
        </div>